# Generated by Django 3.2.7 on 2021-09-30 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singerimage',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='musicimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='music.music'),
        ),
    ]
